# .goreleaser.yaml
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - 386
    - amd64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archive:
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    linux: Linux
    amd64: x86_64
nfpms:
  -
    name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/dimelo/puma-helper
    description: Puma-Helper CLI aims to implement missing centralized and human readeable features from puma unix socket in one place.
    maintainer: Valentin Pichard <valentin.pichard@dimelo.com>
    license: MIT
    vendor: Puma-Helper
    formats:
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - rpm
